name: Release Helm Charts

on:
  push:
    branches:
      - main  # main 브랜치로의 푸시를 트리거로 설정

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.7.0  # 사용할 Helm 버전

      - name: Package Helm chart
        run: helm package ./charts/myapp  # Helm 차트 패키징

      - name: Upload Helm chart to repository
        run: |
          helm repo index . --url https://siamese-lang.github.io/helm-repo-test  # Helm 레포지토리 인덱스 업데이트
          git config --global user.email "you@example.com"
          git config --global user.name "your_username"
          git add .
          git commit -m "Update Helm chart"
          git push origin main  # 변경 사항 푸시
      
      - name: Install Helm chart
        run: |
          helm repo add siamese https://siamese-lang.github.io/helm-repo-test  # Helm 레포지토리 추가
          helm repo update  # 레포지토리 업데이트
          helm install myapp siamese/myapp  # 차트 설치
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GITHUB_TOKEN 환경변수로 사용
